[project]
name = "adamix-me"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Adam Burdík", email = "adamburdik9@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "uvicorn[standard]>=0.52.1",
]

[project.scripts]
adamix-me = "adamix_me:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[tool.vercel]
entrypoint = "src.adamix_me:app"
